---

- hosts: all
  become: true

  tasks:

    - name: Import Vars
      include_vars:
        file: group_vars/all.yml

    - name: dependa install
      become: true
      import_tasks: imports/dependa.yml
      tags: [ dependas ]

    - name: build plugin depend install
      include_tasks: includes/build_depend.yml
      tags: [ build_plugin_depend ]

    - name: Clone Caldera
      include_tasks: includes/install.yml
      register: result
      tags: [ caldera ]

    - name: Clone Pathfinder into caldera
      include_tasks: includes/pathfinder.yml
      tags: [ pathfinder ]

    - name: Create SSH Keypair In Conf File if not Present
      include_tasks: includes/ssh_keygen.yml
      tags: [ ssh_keygen ]

    - name: Setup Default File
      include_tasks: includes/setup_default_file.yml
      tags: [ setup_default ]

    - name: Launch Caldera
      include_tasks: includes/launch.yml
      tags: [ launch ]

    - name: Get Password
      shell: "/bin/bash -c 'sleep 120s'; /bin/cat {{ caldera_install_root_dir }}/caldera/conf/local.yml | grep 'red:'"
      register: details

    - name: Print Details 
      debug: msg="Red PassWord/:{{ details.stdout.replace('\\"',':').split('\n') }}"

