---

- hosts: all
  become: true

  tasks:

    - name: "Check if /usr/bin/python exists"
      stat:
        path: '/usr/bin/python'
      register: python_stat

    - name: symlink /usr/bin/python -> /usr/bin/python3
      raw: |
        if [ -f /usr/bin/python3 ] && [ ! -f /usr/bin/python ]; then
          ln --symbolic /usr/bin/python3 /usr/bin/python; 
        fi
      when: python_stat.stat.exists == false

    - name: Import Vars
      include_vars:
        file: group_vars/all.yml

    - name: dependa install
      become: true
      import_tasks: imports/dependa.yml
      tags: [ dependas ]

    - name: build plugin depend install
      include_tasks: includes/build_depend.yml
      tags: [ build_plugin_depend ]

    - name: Clone Caldera
      include_tasks: includes/install.yml
      register: result
      tags: [ caldera ]

    - name: Clone Pathfinder into caldera
      include_tasks: includes/pathfinder.yml
      tags: [ pathfinder ]

    - name: Create SSH Keypair In Conf File if not Present
      include_tasks: includes/ssh_keygen.yml
      tags: [ ssh_keygen ]

    - name: Setup Default File
      include_tasks: includes/setup_default_file.yml
      tags: [ setup_default ]

    - name: Launch Caldera
      include_tasks: includes/launch.yml
      tags: [ launch ]
